application: buzzwatching
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images
- url: /css
  static_dir: static/css
- url: /bgtasks
  script: index.py
  login: admin
- url: /.*
  script: index.py
